/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EXAToken__factory } from "./EXAToken__factory";
export { TokenRecipient__factory } from "./TokenRecipient__factory";
