/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  TokenRecipient,
  TokenRecipientInterface,
} from "../../../contracts/EXAToken.sol/TokenRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_extraData",
        type: "bytes",
      },
    ],
    name: "receiveApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class TokenRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): TokenRecipientInterface {
    return new Interface(_abi) as TokenRecipientInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TokenRecipient {
    return new Contract(address, _abi, runner) as unknown as TokenRecipient;
  }
}
