/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as exaTokenSol from "./EXAToken.sol";
export type { exaTokenSol };
export type { TestToken } from "./TestToken";
